config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :employees
  resources :packages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
	has_one :salary

	has_many :employee_packages,dependent: :destroy       # for many use (packages) for single use (package)
	has_many :packages , through: :employee_packages



# def self.search(search, page)
#   paginate :per_page => 5, :page => page,
#            :conditions => ['employee_name like ?', "%#{search}%"],
#            :order => 'employee_name'
# end



	mount_uploader :avatar, AvatarUploader   # for single image
    mount_uploaders :avatars, AvatarUploader   # for multiple image 
    serialize :avatars, JSON 

# here we write column_name of table employee_name & phone_number is column in employee table .this is 
# server side validation check before insert data into table to check data must be correct.
# , on: :create   use this is want validation on creatig new record & on: :update when update if want on both 
# write nothing
    validates :employee_name,presence: true,uniqueness: true
	validates :phone_number, presence: true,length: {message:"phone number should be of 10 digits" , is:10 }
end

app/models/employee_package.rb
class EmployeePackage < ApplicationRecord
	belongs_to :employee
	 belongs_to :package
end

app/models/package.rb
class Package < ApplicationRecord
	has_many :employee_packages,dependent: :destroy
	has_many :employees , through: :employee_packages

	validates :package_price,presence: true,:numericality => {:only_integer => true}
	validates :package_name,presence: true,uniqueness: true
end

app/models/salary.rb
class Salary < ApplicationRecord
	  belongs_to :employee
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

	def index
   @employees = Employee.paginate(:page => params[:page], :per_page => 5) #-- pagination using will gem



#------- tell us the all the employees associated with package id= 1 means small
# @package = Package.find(1)
# @employees = @package.employees   # use employees here not employee bcaz packages has_many employees
# render json: @employees
#--------------------------------------------------------------------------


#------- tell us the all the packages associated with employee id= 1 
# @employee = Employee.find(1)
# @packages = @employee.packages   # use packages here not package bcaz employee has_many packages
# render json: @packages
#--------------------------------------------------------------------------


	end
#--------------------------------------------------#

	def new
   @employee = Employee.new
    # @packages = Package.all
	end	
#--------------------------------------------------#
	def create

     # @employee = Employee.new(insert_param)		
  
    @employee = Employee.new

  @employee.employee_name = params[:employee][:employee_name]
   @employee.email = params[:employee][:email]
  @employee.phone_number = params[:employee][:phone_number]
  @employee.avatars = params[:employee][:image]                 # for multiple file use avatars
 # @employee.avatar = params[:employee][:image]                # for single file use this 

 
 @salary = params[:employee][:salary]

      # packages  =   params[:employee][:packages].map(&:inspect).join(', ')

    packages = params[:employee][:packages]   # packages is an array collection of ids

     
# render json: @employee                                       #only data we filed is show not save in db.
 
if @employee.save

#render json: @employee                                          #  now whole data of record which created just comes from db 

UserMailer.with(employee: @employee).welcome_email.deliver_now    #Sends email to user when user is created

@salary =  Salary.new(salary: @salary)                             # create object of salary table
@employee.salary  = @salary                                       # it insert salary 10000 into salary table 
                                                      #and  employe_id = @employee.id(mylb jo emp create hoga)

# @emp = Employee.find_by(email: params[:email])

packages.each do |package| 
@employee.employee_packages.create!(package_id: package)
end

# the above line insert data into employee_package.. single user have multiple packages...
# @employee means insert package for a particular employee whose value is in @employeee

render json: @employee.packages

else
render 'new'
end

 end 

#---------------------------------#
 def show
@employee = Employee.find(params[:id])          #get all detail of cstomer from his id.

end
#---------------------

   def edit
  @employee = Employee.find(params[:id])
   end

#--------------------------------------------------#
   def update
  @employee = Employee.find(params[:id])
   @employee.employee_name = params[:employee][:employee_name]
  @employee.phone_number = params[:employee][:phone_number]
  @employee.avatars = params[:employee][:image]       \

  if @employee.save
    
    redirect_to employees_path 

   else
    render 'edit'
     end

   end

#--------------------------------------------------#

   def destroy
 
   @employee = Employee.find(params[:id])
   @employee.destroy

 redirect_to employees_path
   end

#--------------------------------------------------#


	private
	def insert_param
     params.require(:employee).permit(:employee_name, :phone_number)
	end	
#--------------------------------------------------#
end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController
	def index
       @packages = Package.all
        render json: @packages
	end	
       
       def new
        @package = Package.new

       end

       def create 
       @package = Package.new(insert_params)

       if @package.save
       	render json:@package
         else
         	render 'new'
             end
    
       end

      private
      
      def insert_params
     params.require(:package).permit(:package_name,:package_price)
      end 

end

app/controllers/test_controller.rb
class TestController < ApplicationController

def index
	render json: UserMailer.welcome_email('shivam.j@applify.co').deliver_now

end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/employees/data.html.erb
5c81552c225f8ff3798eb50323bb2129-secret
531518800620388-app id


477948166054310-app id for test app
02016b925af0b2908b4e070ff97eb2bd-secret

app/views/employees/edit.html.erb
<%= form_with model: @employee, local: true do |form| %>
  <p>
    <%= form.label :employee_name %><br>
    <%= form.text_field :employee_name %>
  </p>
 
  <p>
    <%= form.label :phone_number %><br>
    <%= form.text_field :phone_number %>
  </p>

<h3>Images are:</h3>
<% @employee.avatars.each do |avatar| %>
 <%= image_tag avatar.thumb.url ? avatar.thumb.url : ''  %> 
 <%end %> 
  <p>
    <%= form.label :image %><br>
    <%= form.file_field :image, multiple: true %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>

   <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@employee.errors.count, "error") %> prohibited
        this employee from being saved:
      </h2>
      <ul>
        <% @employee.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<%= link_to 'back' ,employees_path %>
<% end %>

app/views/employees/index.html.erb
<table>
<tr>
	<th>
		id
	</th>
          <th>
		employee_name
	</th>
	<th>
		phone_number
	</th>
         <th>
		images
	</th>
	<th>
    Actions
    </th>
</tr>
<% @employees.each do |employee| %>
<tr>
	<td>
	<%=	employee.id %>
	</td>
	<td>
	<%=	employee.employee_name %>
	</td>
	<td>
	<%=	employee.phone_number %>
	</td>
	<td>
    <% employee.avatars.each do |avatar| %>
	<%= image_tag avatar.thumb.url ? avatar.thumb.url : ''  %>
	<% end %>
	</td>
	<td>
		<%= link_to 'delete', employee_path(employee),method: :delete,data: { confirm: 'Are you sure?' }  %>
		<%= link_to 'edit' ,edit_employee_path(employee) %>
		<%= link_to 'new',new_employee_path %>
		<%= link_to 'show', employee_path(employee) %>
	</td>
</tr>
<% end %>
</table>

<%= will_paginate @employees %>

app/views/employees/new.html.erb
<%= form_with scope: :employee,url: employees_path,local: true do |form| %>
  <p>
    <%= form.label :employee_name %><br>
    <%= form.text_field :employee_name %>
  </p>
 
  <p>
    <%= form.label :phone_number %><br>
    <%= form.text_field :phone_number %>
  </p>

 <p>
    <%= form.label :email %><br>
    <%= form.email_field :email %>
  </p>

  <p>
  <%= form.label :salary %><br>
  <%= form.text_field :salary %>
  </p>
                
         
<%= form.collection_check_boxes :packages, Package.all, :id, :package_name, include_hidden: false %>




  <p>
    <%= form.label :image %><br>
    <%= form.file_field :image, multiple: true %>
  </p>


 
  <p>
    <%= form.submit %>
  </p>

   <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@employee.errors.count, "error") %> prohibited
        this employee from being saved:
      </h2>
      <ul>
        <% @employee.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<% end %>

app/views/employees/show.html.erb
<p>
  <strong>id:</strong>
  <%= @employee.id %>
</p>
 
<p>
  <strong>name:</strong>
  <%= @employee.employee_name %>
</p>

<p>
  <strong>phone_number:</strong>
  <%= @employee.phone_number %>
</p>

<p>
  <strong>image:</strong>
  <% @employee.avatars.each do |avatar| %>
  <%= image_tag avatar.thumb.url ? avatar.thumb.url : '' %>
  <% end %>
</p>

<p>
  <strong>salary:</strong>
  <%= @employee.salary ? @employee.salary.salary : 'no record' %>            
</p>

<p>
  <strong>packages:</strong>
  <%  if  @employee.packages != nil    %>
  <% @employee.packages.each do|package| %>
  <%=  package.package_name  %>  
  <% end %> 
  <% else %>
  not exist    
  <% end %>     
</p>

<!-- here @employee.salary result is get record from salary table where employee_id = @employee.id
means jis employee k record show kr rhe hai ex. usiki id -8 hai to salary table mai yha emp_id 8 hai wo
record aa jyga then usme .salary means salary column ki value
 -->

<%= link_to 'back', employees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Firstproject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>